# Generated by Django 4.0.5 on 2022-06-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='option_three',
            field=models.CharField(max_length=100),
        ),
    ]
